//#region User Autehticate action type 
export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
//#endregion

//#region Get User action type
export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_USERS_LOGIN_LOADING = "GET_USERS_LOGIN_LOADING";
export const GET_USERS_LOGIN_SUCCESS = "GET_USERS_LOGIN_SUCCESS";
export const GET_USERS_LOGIN_ERROR = "GET_USERS_LOGIN_ERROR";
//#endregion

//#region Message action type
export const GET_MESSAGES_LOADING = "GET_MESSAGES_LOADING";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";

export const SEND_MESSAGE_LOADING = "SEND_MESSAGE_LOADING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";
//#endregion

//#region Socket action type
export const SOCKET_MESSAGES_SUCCESS = "SOCKET_MESSAGES_SUCCESS";
export const GET_ONLINE_USERS_SUCCESS = "GET_ONLINE_USERS_SUCCESS";
//#endregion

//#region Get Login User action type
export const GET_LOGIN_USER_LOADING = "GET_LOGIN_USER_LOADING";
export const GET_LOGIN_USER_SUCCESS = "GET_LOGIN_USER_SUCCESS";
export const GET_LOGIN_USER_ERROR = "GET_LOGIN_USER_ERROR";
//#endregion

